[package]
name = "comma"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.11"
flume = "0.10.8"
nix = "0.22.0"
num_enum = "0.5.3"
tracing = "0.1.26"
tracing-subscriber = "0.2.19"
